### ISSUE TITLE
Reformat user guide

### ISSUE THREAD

**Issue by jakobbraun** [exasol/bucketfs-java#32]
Currently, the IntelliJ IDEA code formatter breaks the code formatting in the Java listings in the user_guide. After this is fixed, we should reformat the file.

**Comment by jakobbraun** [comment]
They don't plan to fix it: https://youtrack.jetbrains.com/issue/IDEA-269943/Code-blocks-are-highlighted-as-errors-in-Markdown

**Comment by jakobbraun** [comment]
Maybe we just close that ticket?

**Comment by redcatbear** [comment]
Closing ticket since upstream will not fix blocker.
