### ISSUE TITLE
Support TLS

### ISSUE THREAD

**Issue by redcatbear** [exasol/bucketfs-java#35]
## Situation

BucketFS support TLS and in production using encryption is important. The library should support that feature.

## Situation

1. BucketFS Java supports TLS
2. Handbook updated to explain preconditions (like where the certificates come from)

**Comment by kaklakariada** [comment]
It's possible to load custom certificates into a KeyStore: https://stackoverflow.com/questions/18513792/using-sslcontext-with-just-a-ca-certificate-and-no-keystore
